# Implementation of activation funsions in python

---

# relu funsion

Applies the rectified linear unit activation function.

With default values, this returns the standard ReLU activation: `max(x, 0)`, the element-wise maximum of 0 and the input tensor.

Modifying default parameters allows you to use non-zero thresholds, change the max value of the activation, and to use a non-zero multiple of the input for values below the threshold.

In [69]:
import math
import tensorflow as tf

In [70]:
x = [-10, -5, 0.0, 5, 10]

relu_output = tf.keras.activations.relu(x)
print(relu_output)

tf.Tensor([ 0.  0.  0.  5. 10.], shape=(5,), dtype=float32)


In [71]:
def relu(x):
  return max(0,x)

relu(-100)

0

In [72]:
relu(10)

10

# Sigmoid activation function.

- It is defined as: sigmoid(x) = 1 / (1 + exp(-x)).

- For small values (<-5), sigmoid returns a value close to zero, and for large values (>5) the result of the function gets close to 1.

- Sigmoid is equivalent to a 2-element softmax, where the second element is assumed to be zero. The sigmoid function always returns a value between 0 and 1.

+ Arguments

  --x: Input tensor.

In [73]:
x = [-10, -5, 0.0, 5, 10]

relu_output = tf.keras.activations.sigmoid(x)
print(relu_output)

tf.Tensor([4.539787e-05 6.692851e-03 5.000000e-01 9.933072e-01 9.999546e-01], shape=(5,), dtype=float32)


In [74]:
def sigmoid(x):
  return 1 / (1 + math.exp(-x))


sigmoid(1)

0.7310585786300049

In [75]:
sigmoid(100)

1.0

In [76]:
sigmoid(-56)

4.780892883885469e-25

In [77]:
sigmoid(0.5)

0.6224593312018546

# sorfmax funtion

Softmax converts a vector of values to a probability distribution.

The elements of the output vector are in range `[0, 1]` and sum to 1.

Each input vector is handled independently. The `axis` argument sets which axis of the input the function is applied along.

Softmax is often used as the activation for the last layer of a classification network because the result could be interpreted as a probability distribution.

The softmax of each vector x is computed as `exp(x) / sum(exp(x))`.

The input values in are the log-odds of the resulting probability.

Arguments

x: Input tensor.

axis: Integer, axis along which the softmax is applied.

In [78]:
x = [-10, -5, 0.0, 5, 10]

# Convert the list x to a Tensorflow tensor
x_tensor = tf.constant([x])

outputs = tf.keras.activations.softmax(x_tensor)
print(outputs)

tf.Tensor([[2.0472659e-09 3.0384118e-07 4.5094032e-05 6.6925474e-03 9.9326211e-01]], shape=(1, 5), dtype=float32)


# tanh function
Hyperbolic tangent activation function.

It is defined as: tanh(x) = sinh(x) / cosh(x), i.e. tanh(x) = ((exp(x) - exp(-x)) / (exp(x) + exp(-x))).

In [79]:
x = [-10, -5, 0.0, 5, 10]

outputs = tf.keras.activations.tanh(x)
print(outputs)

tf.Tensor([-1.         -0.99990916  0.          0.99990916  1.        ], shape=(5,), dtype=float32)


In [80]:
def tanh(x):
  return (math.exp(x) - math.exp(-x)) / (math.exp(x) + math.exp(-x))

In [81]:
tanh(-56)

-1.0

In [82]:
tanh(-10)

-0.9999999958776926

In [83]:
tanh(50)

1.0

In [84]:
tanh(1)

0.7615941559557649

In [85]:
def softplus(x):
  return math.log(math.exp(x) + 1)

In [90]:
softplus(1)

1.3132616875182228