# Implement Mean Absolute Error
---


In [64]:
import numpy as np
import tensorflow as tf

In [65]:
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

In [66]:
def mae(y_predicted, y_true):
  total_error = 0
  for yp, yt in zip(y_predicted, y_true):
    total_error += abs(yp - yt)
  print('Total error is: ', total_error)
  mae = total_error / len(y_predicted)
  print('Mean absolute error is: ', mae)
  return mae

In [67]:
mae(y_predicted, y_true)

Total error is:  2.5
Mean absolute error is:  0.5


0.5

Implement same thing using numpy in much easier way

In [68]:
np.abs(y_predicted - y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [69]:
np.mean(np.abs(y_predicted - y_true))

0.5

In [70]:
def mae_np(y_predicted, y_true):
  return np.mean(np.abs(y_predicted - y_true))

In [71]:
mae_np(y_predicted, y_true)

0.5

## Imaplement Log Loss or Binary Cross Entropy

In [72]:
np.log([2])

array([0.69314718])

In [73]:
epsilon = 1e-15

np.log([epsilon])

array([-34.53877639])

In [74]:
y_predicted

array([1, 1, 0, 0, 1])

In [75]:
y_predicted_new = [max(i,epsilon) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [76]:
1 - epsilon

0.999999999999999

In [77]:
y_predicted_new = [min(i, 1 - epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [78]:
y_predicted_new = np.array(y_predicted_new)

In [79]:
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [80]:
-np.mean(y_true*np.log(y_predicted_new) + (1 - y_true)*np.log(1 - y_predicted_new))

17.2696280766844

In [90]:
def log_loss(y_true, y_predicted, epsilon):
  y_predicted_new = [max(i,epsilon) for i in y_predicted]
  y_predicted_new = [min(i, 1 - epsilon) for i in y_predicted_new]
  y_predicted_new = np.array(y_predicted_new)
  return (-np.mean(y_true*np.log(y_predicted_new) + (1 - y_true)*np.log(1 - y_predicted_new)))

In [91]:
log_loss(y_true, y_predicted, epsilon)

17.2696280766844

# Implement Mean Squared Error Funsion in Python
---



In [92]:
y_predicted_mse = np.array([1,1,0,0,1])
y_true_mse = np.array([0.30,0.7,1,0,0.5])

In [93]:
def mse(y_true_mse, y_predicted_mse):
  total_error = 0
  for yt, yp in zip(y_true_mse, y_predicted_mse):
    total_error += (yt - yp)**2
  print('Total Squared Error: ',total_error)
  mse = total_error/len(y_true_mse)
  print('Mean Squared Error: ', mse)
  return mse

In [94]:
mse(y_true_mse, y_predicted_mse)

Total Squared Error:  1.83
Mean Squared Error:  0.366


0.366

In [96]:
np.mean(np.square(y_true_mse - y_predicted_mse))

0.366

In [99]:
def mse_np(y_true,y_predicted):
  return np.mean(np.square(y_true - y_predicted))


In [100]:
mse_np(y_true_mse, y_predicted_mse)

0.366